spring.application.name=techcup-futbol

server.port=8085

logging.level.root=INFO

logging.level.edu.dosw.proyect=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

#Swagger
#spring.mvc.pathmatch.use-suffix-pattern=false
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html