spring.config.import=optional:file:.env[.properties]

server.port=8085
logging.level.root=INFO
logging.level.edu.dosw.proyect=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Database Configuration 
spring.datasource.url=jdbc:postgresql://localhost:5432/techcup_db
spring.datasource.username=postgres
spring.datasource.password=Lauravale0201
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
jwt.secret=techcup-super-secret-key-change-in-production-environment-2024
jwt.expiration=86400000
jwt.refresh-expiration=604800000
